site_name: BlvckBytes
site_url: https://www.blvckbytes.at

nav:
  - Home: index.md
  - About Me: about.md
  - Math:
    - Binomial Expansion: math/binomial_expansion.md
    - Pythagorean Theorem: math/pythagorean_theorem.md

theme:
  name: terminal
  palette: dark
  features:
  - footer.prev_next
  custom_dir: overrides

markdown_extensions: 
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - css/overrides.css