site_name: BlvckBytes
site_url: https://www.blvckbytes.at

nav:
  - Home: index.md
  - About Me: about.md
  - Math:
    - Personal Goal: math/personal_goal.md
    - DIN A Paper Sizes: math/din_a_paper_sizes.md
    - Binomial Expansion: math/binomial_expansion.md
    - Pythagorean Theorem: math/pythagorean_theorem.md
    - Truncated Cone Volume: math/truncated_cone_volume.md
    - Euclids Theorem Of Sides: math/euclids_theorem_of_sides.md
    - Archimedes' Pi Approximation: math/archimedes_pi_approximation.md
    - Roman Numerals: math/roman_numerals.md
    - Orthogonal Circles: math/orthogonal_circles.md
    - Triangles: math/triangles.md
    - Angles: math/angles.md
    - Thales' Half Circle Theorem: math/thales_half_circle_theorem.md
  - Puzzles:
    - Three Circles In A Square: puzzles/three_circles_in_a_square.md
    - Circle Sectors Intersect In A Square: puzzles/circle_sectors_intersect_in_a_square.md
  - Philosophy:
    - Chained To A Madman: philosophy/chained_to_a_madman.md
    - The Ultimate Schematic: philosophy/the_ultimate_schematic.md
    - The Agonizing Reach For Greatness: philosophy/the_agonizing_reach_for_greatness.md

theme:
  name: terminal
  palette: dark
  features:
  - footer.prev_next
  custom_dir: overrides

markdown_extensions: 
  - pymdownx.arithmatex:
      generic: true
  - markdown.extensions.attr_list:
  - toc:
      toc_depth: "2"

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/hljs/highlight.min.js
  - javascripts/hljs/languages/java.min.js
  - javascripts/hljs/languages/python.min.js
  - javascripts/hljs/languages/javascript.min.js
  - javascripts/hljs/languages/typescript.min.js
  - javascripts/hljs/init.js

extra_css:
  - css/overrides.css
  - css/hljs/github-dark-dimmed.min.css
